project_rails/config/routes.rb
Project::Application.routes.draw do
  resources :vegetables

  resources :index do
    collection do		  
      get :search
    end
    member do
      get :item
      get :show
      get :csv
      get :csv2
      get :week_csv
    end
  end

  root :to => "index#index"
   

end

project_rails/app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  before_action :set_vegetable, only: [:show, :edit, :update, :destroy]

  # GET /vegetables
  # GET /vegetables.json
  def index
    @vegetables = Vegetable.all
  end

  # GET /vegetables/1
  # GET /vegetables/1.json
  def show
  end

  # GET /vegetables/new
  def new
    @vegetable = Vegetable.new
  end

  # GET /vegetables/1/edit
  def edit
  end

  # POST /vegetables
  # POST /vegetables.json
  def create
    @vegetable = Vegetable.new(vegetable_params)

    respond_to do |format|
      if @vegetable.save
        format.html { redirect_to @vegetable, notice: 'Vegetable was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vegetable }
      else
        format.html { render action: 'new' }
        format.json { render json: @vegetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vegetables/1
  # PATCH/PUT /vegetables/1.json
  def update
    respond_to do |format|
      if @vegetable.update(vegetable_params)
        format.html { redirect_to @vegetable, notice: 'Vegetable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vegetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vegetables/1
  # DELETE /vegetables/1.json
  def destroy
    @vegetable.destroy
    respond_to do |format|
      format.html { redirect_to vegetables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vegetable
      @vegetable = Vegetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
		# 參數白名單
    def vegetable_params
      params.require(:vegetable).permit(:id, :serial, :name, :r_name, :season, :kind, :form)
    end
end

project_rails/app/helpers/vegetables_helper.rb
module VegetablesHelper
end

project_rails/app/views/vegetables/_form.html.erb
<%= form_for(@vegetable) do |f| %>
  <% if @vegetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vegetable.errors.count, "error") %> prohibited this vegetable from being saved:</h2>

      <ul>
      <% @vegetable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :serial %><br>
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :r_name %><br>
    <%= f.text_field :r_name %>
  </div>

  <div class="field">
    <%= f.label :kind %><br>
    <%= f.select :kind , [["無" , nil]] + Vegetable::KIND %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.select :season , [["無" , nil]] + Vegetable::SEASON %>
  </div>
  <div class="field">
    <%= f.label :form %><br>
    <%= f.select :form , [["無" , nil]] + Vegetable::FORM %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project_rails/app/views/vegetables/edit.html.erb
<h1>Editing vegetable</h1>

<%= render 'form' %>

<%= link_to 'Show', @vegetable %> |
<%= link_to 'Back', vegetables_path %>

project_rails/app/views/vegetables/index.html.erb
<h1>Listing vegetables</h1>
<%= link_to 'New Vegetable', new_vegetable_path %>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Serial</th>
      <th>Name</th>
      <th>R name</th>
			<th>kind</th>
			<th>season</th>
			<th>form</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vegetables.each do |vegetable| %>
      <tr>
        <td><%= vegetable.id %></td>
        <td><%= vegetable.serial %></td>
        <td><%= vegetable.name %></td>
        <td><%= vegetable.r_name %></td>
        <td><%= vegetable.kind ? Vegetable::KIND[vegetable.kind][0] : '無' %></td>
        <td><%= vegetable.season ? Vegetable::SEASON[vegetable.season][0] : '無' %></td>
			  <td><%= vegetable.form ? Vegetable::FORM[vegetable.form][0] : '無' %></td>
        <td><%= link_to 'Show', vegetable %></td>
        <td><%= link_to 'Edit', edit_vegetable_path(vegetable) %></td>
        <td><%= link_to 'Destroy', vegetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

project_rails/app/views/vegetables/new.html.erb
<h1>New vegetable</h1>

<%= render 'form' %>

<%= link_to 'Back', vegetables_path %>

project_rails/app/views/vegetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @vegetable.id %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @vegetable.serial %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vegetable.name %>
</p>

<p>
  <strong>R name:</strong>
  <%= @vegetable.r_name %>
</p>

<%= link_to 'Edit', edit_vegetable_path(@vegetable) %> |
<%= link_to 'Back', vegetables_path %>